### ISSUE TITLE
ReferenceError: $subject is not defined

### ISSUE THREAD

**Issue by adamcohen** [stalniy/bdd-lazy-var#44]
I must be doing something silly, but the following doesn't work for me, taken directly from the example:

**my_spec.js**

```javascript
const chai = require('chai')
const expect = chai.expect
const Mocha = require('mocha');

const mocha = new Mocha({
  ui: 'bdd-lazy-var/global'
});

const { get, def } = require('bdd-lazy-var/global');

describe('Array', () => {
  subject(() => [1, 2, 3]);

  it('has 3 elements by default', () => {
    expect($subject).to.have.length(3);
  });
});
```

**Test result**
```
./node_modules/.bin/mocha -u bdd-lazy-var test/my_spec.js

  Array
    1) has 3 elements by default


  0 passing (7ms)
  1 failing

  1) Array
       has 3 elements by default:
     ReferenceError: $subject is not defined
      at Context.it (test/my_spec.js:14:12)
```

Using: 

```
node v9.11.1

"bdd-lazy-var": "2.2.3",
"chai": "4.1.2",
"mocha": "5.1.1",
```

**Comment by adamcohen** [comment]
Thanks for the response @stalniy, as well as for working on this project!  It works now with the following:

```javascript
const chai = require('chai')
const expect = chai.expect

describe('Array', () => {
  subject(() => [1, 2, 3]);

  it('has 3 elements by default', () => {
    expect($subject).to.have.length(3);
  });
});
```

However, I'm confused by the documentation.  It says in [installation](https://github.com/stalniy/bdd-lazy-var#installation):

> Command line
> `mocha -u bdd-lazy-var`
>
> In JavaScript
> `const Mocha = require('mocha');` ...

Is this an either/or setup?  Is it possible to use `bdd-lazy-var` in Javascript without needing to specify `-u bdd-lazy-var/global` on the command line?  If not, what is the purpose of the `In JavaScript` setup?  Also, Why is the command listed as `mocha -u bdd-lazy-var`, but you said to use `-u bdd-lazy-var/global`?  Thanks!

**Comment by stalniy** [comment]
So, there are [3 different dialects](https://github.com/stalniy/bdd-lazy-var#dialects). Each dialect has its own file. That's why you need to configure mocha differently based on which dialect you want to use.

if you want to use `global` dialect, you need to require `bdd-lazy-var/global` (i.e., pass as `ui` to mocha). For `getter` dialect, you need to require `bdd-lazy-var/getter` and for the most simple default, just add `bdd-lazy-var`.

You used the most strict dialect which allows to use only `get`, `subject` and `def` helpers and which doesn't define variables in global scope.

Another point is that mocha, jest and jasmine can be used as command line tools or as libraries (for cases when you want to create your own cli script), that's why there are 2 section: one for JavaScript another one for CLI

**P.S.**: I plan update description for mocha because others uses `bdd-lazy-var/global` and only mocha uses `bdd-lazy-var`

**Comment by stalniy** [comment]
Updated docs, hopefully it makes sense :)

**Comment by adamcohen** [comment]
@stalniy thanks for the explanation and updates to the docs, it all makes sense now!
